/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.list;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class ArrayLinkedListTest {
    @Test void testConstructor() {
        ArrayLinkedList<String> list = new ArrayLinkedList<>();
        assertEquals(0, list.getSize());
    }

    @Test void testAdd() {
        ArrayLinkedList<String> list = new ArrayLinkedList<>();

        list.add("one");
        assertEquals(1, list.getSize());
        assertEquals("one", list.get(0));

        list.add("two");
        assertEquals(2, list.getSize());
        assertEquals("two", list.get(1));
    }

    @Test void testRemove() {
        ArrayLinkedList<String> list = new ArrayLinkedList<>();

        list.add("one");
        list.add("two");
        assertTrue(list.remove(0));

        assertEquals(1, list.getSize());
        assertEquals("two", list.get(0));

        assertTrue(list.remove(0));
        assertEquals(0, list.getSize());
    }

    @Test public void testRemoveMissing() {
        ArrayLinkedList<String> list = new ArrayLinkedList<>();

        list.add("one");
        list.add("two");
        assertFalse(list.remove(2));
        assertEquals(2, list.getSize());
    }
}
