/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import java.io.IOException;

public class CheckerApp {
    public static void main(String[] args) throws IOException {
        Checker checker = new Checker(new HappyTickets(), "/happy-tickets/", "/happy-tickets/");
    }
}
