/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.junit.jupiter.api.Test;

class SquareSpellsTest {
    public static final int N = 25;
    
    @Test
    void testSpell2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x == y) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell3() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x == N - 1 - y) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell4() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x + y < 30) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell5() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (Math.floor(x / 2) == y) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell6_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x < 10 || y < 10) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    public void testSpell6_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (y - 10 >= 0 && x - 10 >= 0) {
                    System.out.print(". ");
                } else {
                    System.out.print("# ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell7_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x > 15 && y > 15) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell7_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x < N - 9 || y < N - 9) {
                    System.out.print(". ");
                } else {
                    System.out.print("# ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell8_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x == 0 || y == 0) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell8_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x * y == 0) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell9_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (Math.abs(x - y) > 10) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell9_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (y - 11 - x >= 0 || x - 11 - y >= 0) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell10_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (y < x && x <= y*2+1) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell10_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (Math.floor(x / (y + 1)) == 1) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell11() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x == 1 || y == 1 || x == 23 || y == 23) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test
    void testSpell12() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x*x + y*y <= 400) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test 
    void testSpell13_1() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x >= N-y-5 && x <= N-y+3) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test 
    void testSpell13_2() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (x + y >= 20 && x + y <= 28) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test 
    void testSpell14() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if ((N-x)*(N-x) + (N-y)*(N-y) <= 21*21) {
                    System.out.print(". ");
                } else {
                    System.out.print("# ");
                }
            }
            System.out.println();
        }
    }
    
    
    @Test 
    void testSpell15() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (Math.abs(x - y) >= 10 && Math.abs (x - y) <= 20) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
    
    @Test 
    void testSpell16() {
        for (int y = 0; y < N; y ++) {
            for (int x = 0; x < N; x ++) {
                if (Math.abs(x - 12) + Math.abs(y - 12) < 10) {
                    System.out.print("# ");
                } else {
                    System.out.print(". ");
                }
            }
            System.out.println();
        }
    }
}
