/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.checker;

import java.io.IOException;

import org.example.lesson3.Fib;

public class CheckerApp {
    public static void main(String[] args) throws IOException {
        //Checker checker = new Checker(new HappyTickets(), "/happy-tickets/", "/happy-tickets/");
        //Checker checker = new Checker(new Pow(), "/pow/", "/pow/");
        Checker.check(new Fib(), "/fibs/", "/fibs/");
    }
}
