/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.checker;

import java.io.IOException;

import org.example.bits.chesse.HorseProblem;

public class CheckerApp {
    public static void main(String[] args) throws IOException {
        //Checker checker = new Checker(new HappyTickets(), "/happy-tickets/", "/happy-tickets/");
        //Checker checker = new Checker(new Pow(), "/pow/", "/pow/");
        //Checker.check(new Fib(), "/fibs/", "/fibs/");
        //Checker.check(new Primes(), "/primes/", "/primes/");
        //Checker.check(new SelectionSort(), "/sort/", "/sort/");
        // Checker.check(new HeapSort(), "/sort/", "/sort/");
        
       // Checker.check(new KingProblem(), "/bits/chesse/king/", "/bits/chesse/king/");
        Checker.check(new HorseProblem(), "/bits/chesse/horse/", "/bits/chesse/horse/");
    }
}
